### ISSUE TITLE
[aiflow] the objective of “workflow” table?

### ISSUE THREAD

**Issue by ryantd** [alibaba/flink-ai-extended#102]
There are no actual things to do with the workflow table, what's the objective of this? You guys will remove or re-design this table shortly?

**Comment by SteNicholas** [comment]
@ryantd , the worflow table is used to persist the metadata of workflow. Users could get the metadata of the workflow on another worflow.

**Comment by ryantd** [comment]
@SteNicholas appreciate your answer, and yes, understood what your thinking. However in your repo, I don't find any data that will save into the "workflow" table, all of the "metadata of workflow" have been already saved into the "workflow_execution" table.
