### ISSUE TITLE
What is the difference between train and inference interfaces?

### ISSUE THREAD

**Issue by LittleBBBo** [alibaba/flink-ai-extended#13]
The api in TFUtils **distinguishes** between **train** and **inference**, but the two interfaces are basically the **same** in terms of usage, parameters, and return values. Even if they are **freely replaced** during use, they can run normally. So, what is the reason for distinguishing these two apis? 
```java
public static <IN, OUT> DataStream<OUT> train(StreamExecutionEnvironment streamEnv, DataStream<IN> input,
			TFConfig tfConfig, TypeInformation<OUT> outTI) throws IOException;

public static <IN, OUT> DataStream<OUT> inference(StreamExecutionEnvironment streamEnv, DataStream<IN> input,
			TFConfig tfConfig, TypeInformation<OUT> outTI) throws IOException;
```

In my opinion, Flink-AI-Extended just plays the role of environment coordination and task scheduling, and the actual running mode should be decentralized to **Python** to manage and **configure through super parameters**. I think we can replace the current train/inference with **invoke(args...)**, which is more succinct and unified at the api level. I don't know if there is any inappropriate place in the implementation?

**Comment by wuchaochen** [comment]
Train and Inference have the same input parameters。Train job may not have output。
