### ISSUE TITLE
[Flink AI FLow][Airflow 2.0] Dag processor hung

### ISSUE THREAD

**Issue by jiangxin369** [alibaba/flink-ai-extended#149]
现象：进程卡住，无法解析dag file，dump 栈信息如下
![image](https://user-images.githubusercontent.com/21049075/112272294-fc507580-8cb6-11eb-8845-e80795e1ff07.png)

**Comment by wuchaochen** [comment]
airflow 添加配置项解决
[core]
mp_start_method = forkserver
