### ISSUE TITLE
Python version >= 3.5 required Error

### ISSUE THREAD

**Issue by ChenShuai1981** [alibaba/flink-ai-extended#24]
When I execute script "/opt/work_home/docker/flink/create_venv.sh" in venv-build image, it raised the following errors. How to fix it?

> New python executable in /opt/work_home/temp/test/tfenv/bin/python
> Installing setuptools, pip, wheel...
> done.
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
> Collecting grpcio
>   Downloading http://mirrors.aliyun.com/pypi/packages/a5/46/5d08b6e26748ed6f3b5e93d980ea5daa63c3a8200b2ad270645b0e2f9566/grpcio-1.22.0-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
>      |████████████████████████████████| 2.2MB 8.4MB/s 
> Collecting six
>   Downloading http://mirrors.aliyun.com/pypi/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
> Collecting numpy
>   Downloading http://mirrors.aliyun.com/pypi/packages/da/32/1b8f2bb5fb50e4db68543eb85ce37b9fa6660cd05b58bddfafafa7ed62da/numpy-1.17.0.zip (6.5MB)
>      |████████████████████████████████| 6.5MB 2.8MB/s 
>     ERROR: Command errored out with exit status 1:
>      command: /opt/work_home/temp/test/tfenv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-TAcG_0/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-TAcG_0/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
>          cwd: /tmp/pip-install-TAcG_0/numpy/
>     Complete output (5 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-TAcG_0/numpy/setup.py", line 31, in <module>
>         raise RuntimeError("Python version >= 3.5 required.")
>     RuntimeError: Python version >= 3.5 required.
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by tywtyw** [comment]
Hey, i have noticed this error before. Here is the solution: 
In the /flink-ai-extended/docker/flink/create_venv.sh, change this 
`pip install grpcio six numpy wheel mock keras_applications keras_preprocessing`
to
`pip install grpcio six numpy==1.16.4 wheel mock keras_applications keras_preprocessing`
and it will work.

**Comment by ChenShuai1981** [comment]
Thank you, the above problem is resolved.
