### ISSUE TITLE
[Airflow] UI Display for Periodic Job

### ISSUE THREAD

**Issue by bgeng777** [alibaba/flink-ai-extended#245]
### Describe the feature

Show more meaningful info about periodic job
### Describe the solution you'd like

1. show time interval of the periodic job
2. not show "unreached_event"
### Additional context
![image](https://user-images.githubusercontent.com/80749729/117626096-521aa780-b1a9-11eb-81a1-cda4ff169a7b.png)

**Comment by SteNicholas** [comment]
@bgeng777, @jiangxin369, @wuchaochen, the implementation of periodic job should consider the SubGag, which could support periodic scheduling. IMO, the periodic scheduling for SubGag couldn't work for event bases scheduling.
