### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by JamieSlome** [alibaba/flink-ai-extended#304]
Hello,

We recently received a vulnerability disclosure from @b1nslashsh against your repository. I couldn't find a security policy or contactable e-mail to share the vulnerability details with you.

If you can provide me with an e-mail, I can send it over to you? Otherwise, you can view the advisory [here](https://huntr.dev/bounties/1-other-alibaba/flink-ai-extended/).

It is private to only you and the discloser. If you have any questions, here to help!

-- Jamie from huntr.dev

**Comment by b1nslashsh** [comment]
@SteNicholas is problem solved?
