### ISSUE TITLE
[Flink AI Flow] Link of contribution guide in README.md returns 404

### ISSUE THREAD

**Issue by jinxing64** [alibaba/flink-ai-extended#332]
### Describe the bug
Link of contribution guide in README.md returns 404
（https://github.com/alibaba/flink-ai-extended/blob/master/flink-ai-flow/CONTRIBUTING.md）

**Comment by SteNicholas** [comment]
@jinxing64 , would you like to contribute to update this link?

**Comment by jinxing64** [comment]
Sure ~ 
https://github.com/alibaba/flink-ai-extended/pull/337
