### ISSUE TITLE
[Flink AI Flow] Executor support CeleryExecutor

### ISSUE THREAD

**Issue by aqua7regia** [alibaba/flink-ai-extended#463]
### Describe the feature
When we in production scene, CeleryExecutor is used in airflow to handle large scale dag and task run. Now Flink AI Flow only supports LocalExecutor, I think this is fragile and not expandable. Please consider to modify CeleryExecutor's interface to adapt in Flink AI Flow.

**Comment by SteNicholas** [comment]
@aqua7regia , this issue has already been supported in #482 .
