### ISSUE TITLE
Performance issues in flink-ai-flow/ai_flow/test/util/model_util/iris_data_utils.py(P2)

### ISSUE THREAD

**Issue by DLPerf** [alibaba/flink-ai-extended#491]
Hello,I found some performance issues.
**The first one** is in the definition of `csv_input_fn` ,flink-ai-flow/ai_flow/test/util/model_util/iris_data_utils.py,
[dataset = dataset.map(_parse_line)](https://github.com/alibaba/flink-ai-extended/blob/d76d3f607d5903e4727be32da6b1eaa5a6696ba4/flink-ai-flow/ai_flow/test/util/model_util/iris_data_utils.py#L111) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

**The socond one** is in the definition of `process`,.
[tf_session=tf.Session(graph=tf_graph))](https://github.com/alibaba/flink-ai-extended/blob/d76d3f607d5903e4727be32da6b1eaa5a6696ba4/flink-ai-flow/ai_flow/test/util/model_util/test_tensorflow_iris_model.py#L154)  was repeatedly called in [for notification in notifications:](https://github.com/alibaba/flink-ai-extended/blob/d76d3f607d5903e4727be32da6b1eaa5a6696ba4/flink-ai-flow/ai_flow/test/util/model_util/test_tensorflow_iris_model.py#L144) and was not closed.
I think it will increase the efficiency and avoid out of memory if you close this session after using it.

Here are two files to support this issue,[support1](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/Session.html#close) and [support2](https://stackoverflow.com/questions/48051647/tensorflow-how-to-perform-image-categorisation-on-multiple-images)

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by jiangxin369** [comment]
Hi @DLPerf，it seems make sense, please create the PR if you are interested in.
