### ISSUE TITLE
对python3何时会支持？另外对pytorch的支持度如何？

### ISSUE THREAD

**Issue by xiangwangjianghu** [alibaba/flink-ai-extended#50]
## 如题，支持python3早有计划，何时能够发布，另外我看对pytorch的支持度不如tensorflow，其实现在使用pytorch的也很多了，有加强打算吗？

**Comment by kulame** [comment]
我也有这个疑问　现在python主流都是python3了

**Comment by wuchaochen** [comment]
now support python3
