### ISSUE TITLE
Performance issues in flink-ai-flow/ (by P3)

### ISSUE THREAD

**Issue by DLPerf** [alibaba/flink-ai-extended#517]
Hello! I've found a performance issue in flink-ai-flow/: `batch()` should be called before `map()`, which could make your program more efficient. Here is [the tensorflow document](https://tensorflow.google.cn/guide/data_performance?hl=zh_cn#vectorized_mapping) to support it.

Detailed description is listed below:

- ai_flow/test/util/model_util/iris_data_utils.py /: `.batch(batch_size)`[(here)](https://github.com/alibaba/flink-ai-extended/blob/577bf2eeba171d0bc4e2773a43a5ccafd542eb3c/flink-ai-flow/ai_flow/test/util/model_util/iris_data_utils.py#L114) should be called before `dataset.map(_parse_line)`[(here)](https://github.com/alibaba/flink-ai-extended/blob/577bf2eeba171d0bc4e2773a43a5ccafd542eb3c/flink-ai-flow/ai_flow/test/util/model_util/iris_data_utils.py#L111).
- examples/wide_and_deep/dependencies/python/code/census_dataset.py/: `dataset.batch(batch_size)`[(here)](https://github.com/alibaba/flink-ai-extended/blob/577bf2eeba171d0bc4e2773a43a5ccafd542eb3c/flink-ai-flow/examples/wide_and_deep/dependencies/python/code/census_dataset.py#L194) should be called before `dataset.map(parse_csv, num_parallel_calls=5)`[(here)](https://github.com/alibaba/flink-ai-extended/blob/577bf2eeba171d0bc4e2773a43a5ccafd542eb3c/flink-ai-flow/examples/wide_and_deep/dependencies/python/code/census_dataset.py#L189).

Besides, you need to check the function called in `map()`(e.g., `parse_csv` called in `dataset.map(parse_csv, num_parallel_calls=5)`) whether to be affected or not to make the changed code work properly. For example, if `parse_csv` needs data with shape (x, y, z) as its input before fix, it would require data with shape (batch_size, x, y, z).

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by SteNicholas** [comment]
@DLPerf , if you have the interest on this performance issue, go ahead to create a PR to fix it.
