### ISSUE TITLE
Relationship or difference between Flink AI Extended vs Alink

### ISSUE THREAD

**Issue by Hongbo-Miao** [alibaba/flink-ai-extended#521]
I am wondering what is the relationship or difference between Flink AI Extended and [Alink](https://github.com/alibaba/Alink).

I saw they are both for Flink machine learning from Alibaba.

Appreciate for any explanation, thanks! 😃

**Comment by SteNicholas** [comment]
@Hongbo-Miao , The difference between `Flink AI Extended` and `Alink` is that `the Flink AI Extended` extends Flink to various machine learning scenarios like Tensorflow distribution, AIFlow etc, but the `Alink` is the machine learning algorithm implementation library for Flink.
