### ISSUE TITLE
Any plan to support tf2.0+?

### ISSUE THREAD

**Issue by Fanoid** [alibaba/flink-ai-extended#73]

**Comment by PerkzZheng** [comment]
问题可能在于TF2.0 JAVA API 已经 deprecated了。[**Warning: This API is deprecated and will be removed in a future version of TensorFlow after the replacement is stable**.] 不知道为什么deprecated了
https://www.tensorflow.org/api_docs/java/org/tensorflow/package-summary

**Comment by wuchaochen** [comment]
supported
